name       : vc
version    : 1.2.0
release    : 2
source     :
    - https://github.com/VcDevel/Vc/releases/download/1.2.0/Vc-1.2.0.tar.gz : 11db4d2085a5201b05f383b504d9d818910d9406b47adc893dc08fac306c06e6
license    : LGPL-3.0
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    %patch -p1 < $pkgfiles/gcc6.patch
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    mkdir build && cd build
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% \
           -DTARGET_ARCHITECTURE=generic \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
