name       : vc
version    : 1.4.1
release    : 4
source     :
    - https://github.com/VcDevel/Vc/releases/download/1.4.1/Vc-1.4.1.tar.gz : 68e609a735326dc3625e98bd85258e1329fb2a26ce17f32c432723b750a4119f
license    : BSD-3-Clause
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    mkdir build && cd build
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% \
           -DTARGET_ARCHITECTURE=generic \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
