name       : vc
version    : 1.4.0
release    : 3
source     :
    - https://github.com/VcDevel/Vc/releases/download/1.4.0/Vc-1.4.0.tar.gz : e6cfc056eb3a72a57751e768ba63236ebf2711d267fbd1dc0acfee0ac16fdf68
license    : LGPL-3.0
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    mkdir build && cd build
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% \
           -DTARGET_ARCHITECTURE=generic \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
