name       : vc
version    : 0.7.5
release    : 1
source     :
    - https://github.com/VcDevel/Vc/releases/download/0.7.5/Vc-0.7.5.tar.gz : 64a606c14867fb5eb5efbd5769d273a515c7f8a78743b2d4746efbdab43d3e2c
license    : LGPL-3.0
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    mkdir build && cd build
    %cmake -DLIB_SUFFIX=%LIBSUFFIX% \
           -DTARGET_ARCHITECTURE=generic \
           ..
build      : |
    cd build
    %make
install    : |
    cd build
    %make_install
