name       : vc
version    : 1.4.3
release    : 6
source     :
    - https://github.com/VcDevel/Vc/releases/download/1.4.3/Vc-1.4.3.tar.gz : 988ea0053f3fbf17544ca776a2749c097b3139089408b0286fa4e9e8513e037f
homepage   : https://github.com/VcDevel/Vc
license    : BSD-3-Clause
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    %cmake_ninja .. \
        -DLIB_SUFFIX=%LIBSUFFIX% \
        -DTARGET_ARCHITECTURE=generic
build      : |
    %ninja_build
install    : |
    %ninja_install
