name       : vc
version    : 1.4.2
release    : 5
source     :
    - https://github.com/VcDevel/Vc/releases/download/1.4.2/Vc-1.4.2.tar.gz : 50d3f151e40b0718666935aa71d299d6370fafa67411f0a9e249fbce3e6e3952
homepage   : https://github.com/VcDevel/Vc
license    : BSD-3-Clause
component  : programming
summary    : SIMD Vector Classes for C++
description: |
    SIMD Vector Classes for C++
patterns   :
    - /usr/include/Vc
    - /usr/lib64
setup      : |
    sed -i 's/lib\//lib64\//' $workdir/CMakeLists.txt
    %cmake_ninja .. \
        -DLIB_SUFFIX=%LIBSUFFIX% \
        -DTARGET_ARCHITECTURE=generic
build      : |
    %ninja_build
install    : |
    %ninja_install
